raft-ann-bench images: update conda sooner (#710)
Nightly builds of `rapidsai/raft-ann-bench` failed like this:

> ImportError: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /opt/conda/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-aarch64-linux-gnu.so)

([build link](https://github.com/rapidsai/docker/actions/runs/10739898324/job/29789780257))

I suspect that's because those images use the same pattern for initializing a conda environment that led to the issues described in https://github.com/rapidsai/ci-imgs/issues/185.

This proposes the same fix that we applied in `ci-imgs` (https://github.com/rapidsai/ci-imgs/pull/186).

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Mike Sarahan (https://github.com/msarahan)

URL: https://github.com/rapidsai/docker/pull/710